name: Helm Chart CI/CD

on:
  push:
    branches:
      - main

env:
  HELM_CHART_PATH: /path/to/helm/chart
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
  AWS_REGION: us-west-2

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Lint Helm Chart
      run: helm lint ${{ env.HELM_CHART_PATH }}

    - name: Test Helm Chart
      run: helm test ${{ env.HELM_CHART_PATH }} --logs

    - name: Build Helm Package
      run: helm package ${{ env.HELM_CHART_PATH }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ${{ env.AWS_REGION }} | helm registry login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

    - name: Push Helm Chart to ECR
      run: |
        CHART_VERSION=$(helm show chart ${{ env.HELM_CHART_PATH }} | grep 'version:' | awk '{print $2}')
        helm push ${{ env.HELM_CHART_PATH }} oci://${{ secrets.AWS_ECR_REGISTRY }}/${{ secrets.AWS_ECR_REPOSITORY }} --force

    - name: Increment Chart Version
      run: |
        CURRENT_VERSION=$(helm show chart ${{ env.HELM_CHART_PATH }} | grep 'version:' | awk '{print $2}')
        # Your logic to increment major or minor version goes here
        NEW_VERSION=... 
        sed -i "s/version: ${CURRENT_VERSION}/version: ${NEW_VERSION}/g" ${{ env.HELM_CHART_PATH }}/Chart.yaml

    - name: Commit and Push Chart Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ${{ env.HELM_CHART_PATH }}/Chart.yaml
        git commit -m "Bump chart version to ${NEW_VERSION}"
        git push
